server {
    listen 80;
    listen [::]:80;

    server_name _;

    root /var/www/html;

    location /sqli-test {
        default_type text/plain;
        return 200 "SQLi LAB - Web Server funcionando\n";
    }

    location / {
        try_files $uri =404;
    }
}
